WARNING: Error in initializing MVAPICH2 ptmalloc library.Continuing without InfiniBand registration cache support.
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/SALib-1.3.8.post0.dev39+g2fc1f2c-py3.6.egg/SALib/analyze/delta.py:144: RuntimeWarning: invalid value encountered in double_scalars
  return Vi / np.var(Y)
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/home/jdq2101/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
